// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eshop.DataAccess.DataContext;

#nullable disable

namespace eshop.DataAccess.Migrations
{
    [DbContext(typeof(EshopDbContext))]
    [Migration("20240130093500_create_data")]
    partial class create_data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eshop.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Elektronik"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tekstil"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kırtasiye"
                        });
                });

            modelBuilder.Entity("eshop.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Apple",
                            ImageUrl = "https://cdn.dsmcdn.com/ty1005/product/media/images/prod/PIM/20230929/05/970e9a76-4ce0-4aed-81ce-7b4b8123736a/1_org_zoom.jpg",
                            Name = "Akıllı Saat",
                            Price = 4000m,
                            Stock = 150
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Android",
                            ImageUrl = "https://cdn.dsmcdn.com/ty1005/product/media/images/prod/PIM/20230929/05/970e9a76-4ce0-4aed-81ce-7b4b8123736a/1_org_zoom.jpg",
                            Name = "Samsung A51",
                            Price = 3500m,
                            Stock = 120
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "LCW",
                            ImageUrl = "https://cdn.dsmcdn.com/ty1005/product/media/images/prod/PIM/20230929/05/970e9a76-4ce0-4aed-81ce-7b4b8123736a/1_org_zoom.jpg",
                            Name = "Tişört",
                            Price = 4000m,
                            Stock = 150
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Description = "Defterler",
                            ImageUrl = "https://cdn.dsmcdn.com/ty1005/product/media/images/prod/PIM/20230929/05/970e9a76-4ce0-4aed-81ce-7b4b8123736a/1_org_zoom.jpg",
                            Name = "Defter seti",
                            Price = 400m,
                            Stock = 150
                        });
                });

            modelBuilder.Entity("eshop.Entities.Product", b =>
                {
                    b.HasOne("eshop.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("eshop.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
